### ISSUE TITLE
polaris-sidecar报域名解析失败

### ISSUE THREAD

**Issue by leiwingqueen** [polarismesh/polaris-sidecar#78]
### 1. 问题描述

使用envoy和polaris-sidecar的方式注入到k8s pod中，发现polaris-sidecar一直报这个域名解析失败。

```shell
2024-12-31T15:45:15.171354Z     error   resolver/server.go:311  [agent] all resolvers failed for question from client, question: ;polaris.polaris-system.       IN       AAAA, client: 10.243.201.72:53776, client_network: udp
```

#### service配置

```shell

xxxx@xxxx:~$ kubectl get services -n polaris-system
NAME                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                             AGE
polaris                      LoadBalancer   10.104.106.77   <pending>     8761:30757/TCP,8090:31728/TCP,8091:30086/TCP,8093:31687/TCP,8080:30874/TCP,15010:31238/TCP,8848:32202/TCP,9848:32393/TCP   7d7h
polaris-controller-metrics   ClusterIP      10.98.35.158    <none>        80/TCP                                                                                             7d3h
polaris-sidecar-injector     ClusterIP      10.109.43.221   <none>        443/TCP                                                                                             7d3h
```

#### pod的sidecar配置

```yaml
- env:
    - name: SIDECAR_RECURSE_ENABLE
      value: "true"
    - name: SIDECAR_MESH_ENABLE
      value: "true"
    - name: SIDECAR_METRIC_ENABLE
      value: "true"
    - name: SIDECAR_LOG_LEVEL
      value: info
    - name: SIDECAR_NAMESPACE
      value: test
    - name: POLARIS_ADDRESS
      value: polaris.polaris-system:8091
    - name: SIDECAR_DNS_ROUTE_LABELS
      value: pod-template-hash:9f576545b,project-id:9110,project-name:b-k8s-manager,release:master_b_20241231103155,rpc-service:false,type:project
    - name: SIDECAR_PORT
      value: "15053"
    - name: SIDECAR_DNS_ENABLE
      value: "false"
    - name: SIDECAR_RLS_ENABLE
      value: "true"
    - name: SIDECAR_METRIC_LISTEN_PORT
      value: "15985"
    image: polarismesh/polaris-sidecar:v1.5.1
    imagePullPolicy: IfNotPresent
    name: polaris-sidecar
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      runAsGroup: 1337
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/polaris-sidecar
      name: polaris-socket
    - mountPath: /data/polaris.yaml
      name: polaris-client-config
      subPath: polaris.yaml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-xd7v7
      readOnly: true
```

### 2. 期望结果

能正常解析到域名和使用服务网格的功能

### 3. 相关版本

SERVER_VERSION:polaris-server-v1.18.1
ENVOY_VERSION:v1.26.2
CONTROLLER_VERSION:v1.7.2
SIDECAR_VERSION:v1.5.1

kubernates版本：1.18
